ALTER TABLE "products"
ADD COLUMN IF NOT EXISTS "isWeeklyTrending" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "products"
ADD COLUMN IF NOT EXISTS "rating" DOUBLE PRECISION;

ALTER TABLE "products"
ADD COLUMN IF NOT EXISTS "ratingsCount" INTEGER;

ALTER TABLE "products"
ADD COLUMN IF NOT EXISTS "reviewsCount" INTEGER;
